all: bigsum factorial dynamic

bigsum: bigsum.f90
	gfortran -g -o bigsum bigsum.f90

factorial: factorial.f90
	gfortran -g -o factorial factorial.f90

dynamic: dynamic.f03
	gfortran -g -o dynamic dynamic.f03
