load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="find-all-groups-of-farmland",
  srcs=[
    "find-all-groups-of-farmland.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
  ],
)
