load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="maximum-students-taking-exam",
  srcs=[
    "maximum-students-taking-exam.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
    "//lib/graph:pushRelabel",
  ],
)
