load("@prelude//cxx:cxx.bzl", "cxx_test")

cxx_test(
  name="blockSPSCQueueTest",
  srcs=[
    "blockSPSCQueueTest.cpp",
  ],
  deps=[
    "//gtest:gtest",
    "//lib:exception",
    "//lib/spsc:spsc",
  ],
)


