load("@prelude//cxx:cxx.bzl", "cxx_library")

cxx_library(
    name="num",
    deps=[
    ],
    exported_headers=[
        "num.h",
        "rat.h",
    ],
    visibility=[
        "PUBLIC",
    ],
)

