cxx_binary(
  name="21",
  srcs=[
    "21.cpp",
  ],
  deps=[
    "//lib:header",
    "//lib:init",
    "//lib:robinHood",
    "//lib:string",
    "//gflags:gflags",
    "//advent/lib:aoc",
    "//glog:glog",
  ],
)

