load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "pfordelta_test",
    srcs = ["pfordelta_test.cpp"],
    deps = [
        "//gtest:gtest",
        "//lib/compression:pfordelta",
    ],
)
