load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="ThreeBody",
  srcs=[
    "ThreeBody.cpp"
  ],
  deps=[
    "//lib:header",
  ],
  linker_flags=["-L/usr/lib/x86_64-linux-gnu", "-lGL", "-lGLU", "-lglut"],
)
