cxx_library(
  name="binarySerialization",
  exported_headers=[
    "binarySerialization.h",
  ],
  srcs=[
    "binarySerialization.cpp",
  ],
  exported_deps=[
    ":stream",
  ],
  visibility=[
    'PUBLIC',
  ],
)

cxx_library(
  name="fileIo",
  exported_headers=[
    "fileIo.h",
  ],
  exported_deps=[
    "//lib:header",
    "//lib:noncopyable",
    "//lib:exception",
  ],
  srcs=[
    "fileIo.cpp",
  ],
  visibility=[
    'PUBLIC',
  ],
)

# cxx_library(
#   name="fstreamDeprecated",
#   exported_headers=[
#     "fstreamDeprecated.h",
#   ],
#   srcs=[
#      "fstreamDeprecated.cpp",
#   ],
#   deps=[
#     "//lib:header",
#   ],
#   visibility=[
#     "PUBLIC",
#   ],
# )

# cxx_library(
#   name="zstreamDeprecated",
#   exported_headers=[
#     "zstreamDeprecated.h",
#   ],
#   srcs=[
#      "zstreamDeprecated.cpp",
#   ],
#   deps=[
#     "//lib:header",
#     "//zlib:zlib",
#   ],
#   visibility=[
#     "PUBLIC",
#   ],
# )

cxx_library(
  name="zstream",
  exported_headers=[
    "zstream.h",
  ],
  srcs=[
     "zstream.cpp",
  ],
  exported_deps=[
    "//lib:header",
    "//lib/io:stream",
    "//zlib:zlib",
  ],
  visibility=[
    "PUBLIC",
  ],
)

cxx_library(
  name="csv",
  exported_headers=[
    "csv.h",
  ],
  exported_deps=[
    "//lib:header",
    "//lib:exception",
    "//lib:noncopyable",
    "//lib/io:stream",
    "//lib:string",
  ],
  srcs=[
    "csv.cpp",
  ],
  visibility=[
    "PUBLIC",
  ],
)

cxx_library(
  name="utils",
  exported_headers=[
    "utils.h"
  ],
  srcs=[
    "utils.cpp",
  ],
  exported_deps=[
    "//glog:glog",
    "//lib:header",
    "//lib:string",
    "//lib/io:stream",
  ],
  visibility=[
    'PUBLIC',
  ],
)

cxx_library(
  name="varlen",
  exported_headers=[
    "varlen.h"
  ],
  srcs=[
    "varlen.cpp",
  ],
  exported_deps=[
    ":fileIo",
  ],
  visibility=[
    'PUBLIC',
  ],
)

cxx_library(
  name="structFile",
  exported_headers=[
    "structFile.h",
  ],
  exported_deps=[
    ":fileIo",
  ],
  visibility=[
    'PUBLIC',
  ],
)

cxx_library(
  name="stream",
  exported_headers=[
    "stream.h",
  ],
  exported_deps=[
    ":fileIo",
    "//lib:exception",
    "//lib:header",
    "//lib:noncopyable",
  ],
  srcs=[
    "stream.cpp",
  ],
  visibility=[
    "PUBLIC",
  ],
)
