load("@prelude//cxx:cxx.bzl", "cxx_binary")
load("//armadillo:defs.bzl", "linker_flags")

cxx_binary(
  name="MatrixTest",
  srcs=[
    "MatrixTest.cpp"
  ],
  deps=[
    "//armadillo:armadillo",
    "//lib:header",
    "//lib:random",
    "//lib:timer",
    "//gflags:gflags",
  ],
  linker_flags=linker_flags,
)
