load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="lexicographically-smallest-equivalent-string",
  srcs=[
    "lexicographically-smallest-equivalent-string.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
    "//lib:unionFindDense",
  ],
)
