load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="sort-items-by-groups-respecting-dependencies",
  srcs=[
    "sort-items-by-groups-respecting-dependencies.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
  ],
)
