
cc_binary(
  name="search",
  srcs=[
    "search.cpp",
  ],
  deps=[
    "//lib:header",
    "//lib:init",
    "//lib:string",
    "//gflags:gflags2",
    "//advent/lib:aoc",
    "//glog2:glog",
  ],
)
