# The sources in this directory mix headers and sources of different glog
# releases and do not compile. //glog:glog is kept as the label that most
# targets depend on and forwards to the vendored glog 0.7 in //glog2.
alias(
  name="glog",
  actual="//glog2:glog",
  visibility=[
    'PUBLIC',
  ],
)
