    load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

    http_archive(
        name = "com_github_google_glog",
        strip_prefix = "glog-0.7.1", # Or the relevant version
        urls = ["https://github.com/google/glog/archive/refs/tags/v0.7.1.tar.gz"],
        sha256 = "...", # Replace with the correct SHA256 for your chosen version
    )
