load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="add-edges-to-make-degrees-of-all-nodes-even",
  srcs=[
    "add-edges-to-make-degrees-of-all-nodes-even.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
  ],
)
