load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="minimum-score-of-a-path-between-two-cities",
  srcs=[
    "minimum-score-of-a-path-between-two-cities.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
    "//lib:unionFindDense",
  ],
)
