load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="best-team-with-no-conflicts",
  srcs=[
    "best-team-with-no-conflicts.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
  ],
)
