load("@prelude//cxx:cxx.bzl", "cxx_library")

cxx_library(
    name="aoc",
    srcs=[
        "aoc.cpp",
    ],
    deps=[
        "//lib:header",
    ],
    exported_headers=[
        "aoc.h",
    ],
    visibility=[
        "PUBLIC",
    ],
)

