cxx_library(
    name="aoc",
    srcs=[
        "aoc.cpp",
    ],
    exported_deps=[
        "//lib:header",
    ],
    exported_headers=[
        "aoc.h",
    ],
    visibility=[
        "PUBLIC",
    ],
)

