load("@rules_cc//cc:defs.bzl", "cc_binary")
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name="aoc",
    hdrs=[
        "aoc.h",
    ],
    srcs=[
        "aoc.cpp",
    ],
    deps=[
        "//lib:header",
    ],
    visibility = ["//visibility:public"],
)

