load("@prelude//cxx:cxx.bzl", "cxx_library")

cxx_library(
  name="client",
  srcs=[
    "client.cc",
  ],
  deps=[
    "//pistache:headers",
    "//pistache/common:common",
  ],
  visibility=[
    'PUBLIC',
  ],
)
