load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="808",
  srcs=[
    "808.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:init",
    "//lib:primes",
    "//lib:string",
    "//glog:glog",
  ],
)
