load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="count-pairs-of-similar-strings",
  srcs=[
    "count-pairs-of-similar-strings.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
  ],
)
