cc_binary(
  name="2",
  srcs=[
    "2.cpp",
  ],
  deps=[
    "//lib:header",
    "//lib:init",
    "//lib:string",
    "//gflags:gflags2",
    "//advent/lib:aoc",
    "//glog2:glog",
  ],
)


cc_binary(
  name="3",
  srcs=[
    "3.cpp",
  ],
  deps=[
    "//lib:header",
    "//lib:init",
    "//lib:string",
    "//gflags:gflags2",
    "//advent/lib:aoc",
    "//glog2:glog",
  ],
)

