load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="minimum-absolute-difference-between-elements-with-constraint",
  srcs=[
    "minimum-absolute-difference-between-elements-with-constraint.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
  ],
)
