load("@prelude//cxx:cxx.bzl", "cxx_binary")


cxx_binary(
  name="14",
  srcs=[
    "14.cpp",
  ],
  deps=[
    "//lib:header",
    "//lib:init",
    "//lib:string",
    "//gflags:gflags",
    "//advent/lib:aoc",
  ],
)

