load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name="calculus",
    hdrs=[
        "calculus.h",
    ],
    srcs=[
        "calculus.cpp",
    ],
    visibility = ["//visibility:public"],
    features = ["-lto"],
)
