load("@rules_cc//cc:defs.bzl", "cc_binary")

# //toolchain:clang12_cc_toolchain_config.bzl
# load("@bazel_tools//tools/build_defs/cc:action_names.bzl", "ACTION_NAMES")
# load(
#     "@bazel_tools//tools/cpp:cc_toolchain_config_lib.bzl",
#     "feature",
#     "flag_group",
#     "flag_set",
#     "tool_path",
# )


# load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
# load("@bazel_tools//tools/cpp:toolchain_utils.bzl", "find_cpp_toolchain")

# package(default_visibility = ["//ETFModeling"])


cc_binary(
    name="ETFModeling2",
#   srcs=[
#     "ETFModeling.cpp",
#   ],
#   deps=[
#    "//gflags:gflags2",
#    "//glog2:glog",
#    "//lib:header",
#    "//lib:init",
#    "//lib/thread-pool:thread-pool2",
#    "//lib:matrix",
#    "//lib:random",
#    "//lib/stat:stat2",
#    "//lib:timer",
#    "//lib:stat",
#    "//lib:exception",
#    "//lib/ml:dataframe",
#    "//lib/io:csv",
#    "//lib:file",
#  ],
#  copts = ["-D_GLIBCXX_USE_CXX11_ABI=0"],
#  features = ["-lto"],
#  linkopts = ["-lstdc++"],
#  copts = ["-D_GLIBCXX_USE_CXX11_ABI=0", "-std=c++17"],
#  visibility = ["//ETFModeling:ETFModeling2"],
)
