cc_library(
    name="easybmp",
    srcs=[
        "EasyBMP.cpp",
    ],
    hdrs=[
        "EasyBMP.h",
        "EasyBMP_BMP.h",
        "EasyBMP_DataStructures.h",
        "EasyBMP_VariousBMPutilities.h",
    ],
    includes=["."],
    # copts=["-stb=c++23"],
    visibility = ["//visibility:public"],
)
