load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="sort-characters-by-frequency",
  srcs=[
    "sort-characters-by-frequency.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
  ],
)
