load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="prime-subtraction-operation",
  srcs=[
    "prime-subtraction-operation.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
  ],
)
