
cxx_binary(
  name="25",
  srcs=[
    "25.cpp",
  ],
  deps=[
    "//lib:header",
    "//lib:init",
    "//lib:string",
    "//lib:unionFind",
    "//gflags:gflags",
    "//advent/lib:aoc",
    "//glog:glog",
  ],
)

