load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "morphologyTest",
    srcs = ["morphologyTest.cpp"],
    deps = [
        "//gtest:gtest",
        "//lib/russianMorphology:morphology",
    ],
)
