load("@prelude//cxx:cxx.bzl", "cxx_library")

cxx_library(
    name="thread-pool",
    srcs=[
        "threadPool.cpp",
    ],
    exported_headers=[
        "threadPool.h",
    ],
    visibility=[
        "PUBLIC",
    ],
)
