load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name="thread-pool2",
    hdrs = ["threadPool.h"],
    srcs = ["threadPool.cpp"],
    visibility = ["//visibility:public"],
#    deps = [":thread-pool2"],
)


