load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="remove-max-number-of-edges-to-keep-graph-fully-traversable",
  srcs=[
    "remove-max-number-of-edges-to-keep-graph-fully-traversable.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
    "//lib:unionFindDense",
  ],
)
