
cc_library(
  name="yfinanace",
  hdrs=[
    "base.h",
    "benchmark.h",
    "methods.h",
    "requests.h",
    "structures.h",
    "utils.h",
  ],
  srcs=[
    "base.cpp",
    "methods.cpp",
    "requests.cpp",
    "utils.cpp",
  ],
  deps=[
    "//lib:header",
  ],
  visibility = ["//visibility:public"],
  features = ["-lto"],
)
