load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="maximum-profit-in-job-scheduling",
  srcs=[
    "maximum-profit-in-job-scheduling.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
  ],
)
