load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="longest-square-streak-in-an-array",
  srcs=[
    "longest-square-streak-in-an-array.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
  ],
)
