load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="count-subarrays-with-median-k",
  srcs=[
    "count-subarrays-with-median-k.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
  ],
)
