load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="Goldschmidt",
  srcs=[
    "Goldschmidt.cpp"
  ],
  deps=[
    "//glog:glog",
    "//lib:header",
    "//lib:matrix",
    "//lib:random",
    "//lib:timer",
  ],
)

