load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="sum-of-number-and-its-reverse",
  srcs=[
    "sum-of-number-and-its-reverse.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
  ],
)
