load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="satisfiability-of-equality-equations",
  srcs=[
    "satisfiability-of-equality-equations.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
  ],
)
