load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="number-of-provinces",
  srcs=[
    "number-of-provinces.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
    "//lib:unionFindDense",
  ],
)
