load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="erect-the-fence",
  srcs=[
    "erect-the-fence.cpp"
  ],
  deps=[
    "//lib:convexHull",
    "//lib:header",
    "//lib:timer",
  ],
)
