cc_binary(
  name="searchIndex",
  srcs=[
    "searchIndex.cpp",
  ],
  deps=[
    "//lib:header",
    "//lib:init",
    "//lib:string",
    "//gflags:gflags2",
    "//glog2:glog",
  ],
#  linkopts = ["-lgmp"],
)

