load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="checking-existence-of-edge-length-limited-paths",
  srcs=[
    "checking-existence-of-edge-length-limited-paths.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
    "//lib:unionFindDense",
  ],
)
