load("@rules_cc//cc:defs.bzl", "cc_binary")
# load("@rules_cc//cc:defs.bzl", "cc_library")
# load("@rules_license//rules:license.bzl", "license")

cc_binary(
   name="1",
   srcs=[
     "1.cpp",
   ],
   deps=[
     "//lib:header",
   ],
)
