load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="parallel-courses-ii",
  srcs=[
    "parallel-courses-ii.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
    "//glog:glog",
  ],
)
