load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="SortedIterator",
  srcs=[
    "SortedIterator.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:radixSort",
    "//lib:random",
    "//lib:timer",
    "//glog:glog",
  ],
)
