# load("@pybind11_bazel//:build_defs.bzl", "pybind_library")
# load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "262",
    srcs = ["262.cpp"],
    deps = [
        "//lib:header",
        "//lib/easybmp",
    ],
)
