load("@prelude//cxx:cxx.bzl", "cxx_binary")


cxx_binary(
  name="13",
  srcs=[
    "13.cpp",
  ],
  deps=[
    "//lib:header",
    "//lib:init",
    "//lib:geometry",
    "//lib:string",
    "//gflags:gflags",
    "//advent/lib:aoc",
  ],
)

