cxx_library(
    name="tree",
    deps=[
    ],
    exported_headers=[
        "tree.h",
    ],
    visibility=[
        "PUBLIC",
    ],
)



# Shared prelude that solutions include as "../header.h".
cxx_library(
    name="header",
    exported_headers=[
        "header.h",
    ],
    exported_deps=[
        "//lib:header",
        "//lib:timer",
    ],
    visibility=[
        "PUBLIC",
    ],
)
