cxx_library(
    name="spsc",
    exported_headers=[
        "blockSPSCQueue.h",
    ],
    srcs=[
    ],
    exported_deps=[
        "//moodycamel:readerwriterqueue",
    ],
    visibility=[
        "PUBLIC",
    ],
)


