load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="basic-calculator",
  srcs=[
    "basic-calculator.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:exception",
    "//lib:timer",
  ],
)
