load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="remove-nth-node-from-end-of-list",
  srcs=[
    "remove-nth-node-from-end-of-list.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
  ],
)
