# load("//toolchain:cc_toolchain")

package(default_visibility = ["//visibility:public"])


cc_binary(
    name = "gflagsTest",
    srcs = ["test.cpp"],
    hdrs = ["test.h"],
    deps = [
        # "//gflags2:gflags",
        # "@com_github_gflags_gflags//:gflags",
        # Other dependencies
    ],
)
