load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree",
  srcs=[
    "find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
  ],
)
