load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="take-k-of-each-character-from-left-and-right",
  srcs=[
    "take-k-of-each-character-from-left-and-right.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
  ],
)
