load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="minimum-reverse-operations",
  srcs=[
    "minimum-reverse-operations.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
  ],
)
