load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="last-day-where-you-can-still-cross",
  srcs=[
    "last-day-where-you-can-still-cross.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:unionFindDense",
    "//lib:timer",
  ],
)
