load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="Kaboom",
  compiler_flags=[
    "-fopenmp",
  ],
  linker_flags=[
    "-fopenmp",
  ],
  srcs=[
    "Kaboom.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:geometry",
  ],
)
