load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="minimum-time-to-make-rope-colorful",
  srcs=[
    "minimum-time-to-make-rope-colorful.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
  ],
)
