load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="longest-consecutive-sequence",
  srcs=[
    "longest-consecutive-sequence.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
    "//lib:unionFind",
  ],
)
