cc_binary(
    name = "eulerCovMatrix",
    srcs = [
        "CovMatrix.cpp",
    ],
    deps = [
        #"@com_github_google_glog//:glog",
        "//glog:glog2",
        "//lib:header",
        "//lib:matrix",
        "//lib:random",
        "//lib:timer",
    ]
)
