cc_binary(
    name = "foo",
    srcs = ["main.cc"],
    deps = [
        "@com_github_gflags_gflags//:gflags", # If using git_repository
        # Or if using Bzlmod:
        # "@gflags//:gflags",
    ],
)
