load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="greatest-common-divisor-traversal",
  srcs=[
    "greatest-common-divisor-traversal.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
    "//lib:unionFindDense",
  ],
)
