load("@prelude//cxx:cxx.bzl", "cxx_library")

cxx_library(
    name="tqdm",
    exported_headers=[
        "tqdm.h",
        "utils.h",
    ],
    deps=[
    ],
    visibility=[
        "PUBLIC",
    ],
)

