load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="similar-string-groups",
  srcs=[
    "similar-string-groups.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
    "//lib:unionFindDense",
  ],
)
