load("@rules_cc//cc:defs.bzl", "cc_binary")
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_binary(
    name="solution1",
    srcs=[
        "solution1.cpp",
    ],
)

cc_binary(
    name="solution2",
    srcs=[
        "solution2.cpp",
    ],
)
