load("@prelude//cxx:cxx.bzl", "cxx_binary")

cxx_binary(
  name="number-of-great-partitions",
  srcs=[
    "number-of-great-partitions.cpp"
  ],
  deps=[
    "//lib:header",
    "//lib:timer",
  ],
)
