cxx_library(
  name="blockStorage",
  exported_headers=[
    "blockStorage.h",
  ],
  srcs=[
    "blockStorage.cpp",
  ],
  deps=[
    "//lib:exception",
    "//lib:header",
    "//lib/io:file",
  ],
  visibility=[
    'PUBLIC',
  ],
)

